//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServices
    {
        public int Id { get; set; }
        public int AdditionalService_Id { get; set; }
        public int Order_Id { get; set; }
    
        public virtual AdditionalServices AdditionalServices { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
