//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChannels
    {
        public int Id { get; set; }
        public int Channel_Id { get; set; }
        public int Order_Id { get; set; }
    
        public virtual Channels Channels { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
