//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSchedules
    {
        public int Id { get; set; }
        public System.DateTime DueDate { get; set; }
        public int TvShow_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual TvShows TvShows { get; set; }
        public virtual Users Users { get; set; }
    }
}
