//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkiCenter", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class SkiCenter : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse[] WarehousesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse[] Warehouses {
            get {
                return this.WarehousesField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehousesField, value) != true)) {
                    this.WarehousesField = value;
                    this.RaisePropertyChanged("Warehouses");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdEntity", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter))]
    public partial class IdEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Order : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.User AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] OrderElementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.RentTime RentTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.User Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] OrderElements {
            get {
                return this.OrderElementsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderElementsField, value) != true)) {
                    this.OrderElementsField = value;
                    this.RaisePropertyChanged("OrderElements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.RentTime RentTime {
            get {
                return this.RentTimeField;
            }
            set {
                if ((this.RentTimeField.Equals(value) != true)) {
                    this.RentTimeField = value;
                    this.RaisePropertyChanged("RentTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarehouseElement", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class WarehouseElement : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Equipment EquipmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Equipment Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameEntity", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.LittleClient))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Phone))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Equipment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.DictionaryEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.EquipmentType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter))]
    public partial class NameEntity : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Warehouse", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Warehouse : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] EquipmentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] Equipments {
            get {
                return this.EquipmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentsField, value) != true)) {
                    this.EquipmentsField = value;
                    this.RaisePropertyChanged("Equipments");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class User : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Roles RoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Roles Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.LittleClient))]
    public partial class Client : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Sex SexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Sex Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BigClient", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class BigClient : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Client {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.LittleClient[] ChildsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Document[] DocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Phone[] PhonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] RentEquipmentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.LittleClient[] Childs {
            get {
                return this.ChildsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildsField, value) != true)) {
                    this.ChildsField = value;
                    this.RaisePropertyChanged("Childs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Document[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Phone[] Phones {
            get {
                return this.PhonesField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonesField, value) != true)) {
                    this.PhonesField = value;
                    this.RaisePropertyChanged("Phones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] RentEquipments {
            get {
                return this.RentEquipmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentEquipmentsField, value) != true)) {
                    this.RentEquipmentsField = value;
                    this.RaisePropertyChanged("RentEquipments");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LittleClient", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class LittleClient : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Client {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Document : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Series {
            get {
                return this.SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesField, value) != true)) {
                    this.SeriesField = value;
                    this.RaisePropertyChanged("Series");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Phone : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipment", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class Equipment : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.EquipmentSize SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.EquipmentType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.EquipmentSize Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.EquipmentType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DictionaryEntity", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.EquipmentType))]
    public partial class DictionaryEntity : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquipmentType", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity")]
    [System.SerializableAttribute()]
    public partial class EquipmentType : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.DictionaryEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.EquipmentType ParentEquipmentTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.EquipmentType ParentEquipmentType {
            get {
                return this.ParentEquipmentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentEquipmentTypeField, value) != true)) {
                    this.ParentEquipmentTypeField = value;
                    this.RaisePropertyChanged("ParentEquipmentType");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentTime", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity.Enums")]
    public enum RentTime : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hour = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Day = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Week = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mounth = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Roles", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity.Enums")]
    public enum Roles : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manager = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity.Enums")]
    public enum Sex : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Man = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Woman = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquipmentSize", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.DbEntity.Enums")]
    public enum EquipmentSize : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Small = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Middle = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Big = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientModel", Namespace="http://schemas.datacontract.org/2004/07/Artinov.StageOne.SkiService")]
    [System.SerializableAttribute()]
    public partial class ClientModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SkiServiceReference.ISkiService")]
    public interface ISkiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetCenters", ReplyAction="http://tempuri.org/ISkiService/GetCentersResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter[] GetCenters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetCenters", ReplyAction="http://tempuri.org/ISkiService/GetCentersResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter[]> GetCentersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetWarehouses", ReplyAction="http://tempuri.org/ISkiService/GetWarehousesResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse[] GetWarehouses(System.Guid skiCentreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetWarehouses", ReplyAction="http://tempuri.org/ISkiService/GetWarehousesResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse[]> GetWarehousesAsync(System.Guid skiCentreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetQuipmentByWarehouseId", ReplyAction="http://tempuri.org/ISkiService/GetQuipmentByWarehouseIdResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] GetQuipmentByWarehouseId(System.Guid skiCentreId, System.Guid warehouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetQuipmentByWarehouseId", ReplyAction="http://tempuri.org/ISkiService/GetQuipmentByWarehouseIdResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[]> GetQuipmentByWarehouseIdAsync(System.Guid skiCentreId, System.Guid warehouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetClients", ReplyAction="http://tempuri.org/ISkiService/GetClientsResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.ClientModel[] GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetClients", ReplyAction="http://tempuri.org/ISkiService/GetClientsResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.ClientModel[]> GetClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetOrders", ReplyAction="http://tempuri.org/ISkiService/GetOrdersResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[] GetOrders(int count, int skip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetOrders", ReplyAction="http://tempuri.org/ISkiService/GetOrdersResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[]> GetOrdersAsync(int count, int skip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetOrdersByPeriod", ReplyAction="http://tempuri.org/ISkiService/GetOrdersByPeriodResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[] GetOrdersByPeriod(System.DateTime stardDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetOrdersByPeriod", ReplyAction="http://tempuri.org/ISkiService/GetOrdersByPeriodResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[]> GetOrdersByPeriodAsync(System.DateTime stardDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetDocumentsByClientId", ReplyAction="http://tempuri.org/ISkiService/GetDocumentsByClientIdResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Document[] GetDocumentsByClientId(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetDocumentsByClientId", ReplyAction="http://tempuri.org/ISkiService/GetDocumentsByClientIdResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Document[]> GetDocumentsByClientIdAsync(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetCurrentEquipmentsByClientId", ReplyAction="http://tempuri.org/ISkiService/GetCurrentEquipmentsByClientIdResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] GetCurrentEquipmentsByClientId(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetCurrentEquipmentsByClientId", ReplyAction="http://tempuri.org/ISkiService/GetCurrentEquipmentsByClientIdResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[]> GetCurrentEquipmentsByClientIdAsync(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetCurrentRentEquipments", ReplyAction="http://tempuri.org/ISkiService/GetCurrentRentEquipmentsResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] GetCurrentRentEquipments(System.Guid skiCentreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetCurrentRentEquipments", ReplyAction="http://tempuri.org/ISkiService/GetCurrentRentEquipmentsResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[]> GetCurrentRentEquipmentsAsync(System.Guid skiCentreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetCurrentFreeEquipments", ReplyAction="http://tempuri.org/ISkiService/GetCurrentFreeEquipmentsResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] GetCurrentFreeEquipments(System.Guid skiCentreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetCurrentFreeEquipments", ReplyAction="http://tempuri.org/ISkiService/GetCurrentFreeEquipmentsResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[]> GetCurrentFreeEquipmentsAsync(System.Guid skiCentreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetDetailClientInfo", ReplyAction="http://tempuri.org/ISkiService/GetDetailClientInfoResponse")]
        Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient GetDetailClientInfo(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/GetDetailClientInfo", ReplyAction="http://tempuri.org/ISkiService/GetDetailClientInfoResponse")]
        System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient> GetDetailClientInfoAsync(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddSkiCentre", ReplyAction="http://tempuri.org/ISkiService/AddSkiCentreResponse")]
        void AddSkiCentre(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddSkiCentre", ReplyAction="http://tempuri.org/ISkiService/AddSkiCentreResponse")]
        System.Threading.Tasks.Task AddSkiCentreAsync(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddWarehouseToSkiCentre", ReplyAction="http://tempuri.org/ISkiService/AddWarehouseToSkiCentreResponse")]
        void AddWarehouseToSkiCentre(System.Guid skiCenterId, Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddWarehouseToSkiCentre", ReplyAction="http://tempuri.org/ISkiService/AddWarehouseToSkiCentreResponse")]
        System.Threading.Tasks.Task AddWarehouseToSkiCentreAsync(System.Guid skiCenterId, Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/CheckUser", ReplyAction="http://tempuri.org/ISkiService/CheckUserResponse")]
        bool CheckUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/CheckUser", ReplyAction="http://tempuri.org/ISkiService/CheckUserResponse")]
        System.Threading.Tasks.Task<bool> CheckUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddClient", ReplyAction="http://tempuri.org/ISkiService/AddClientResponse")]
        void AddClient(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient newClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddClient", ReplyAction="http://tempuri.org/ISkiService/AddClientResponse")]
        System.Threading.Tasks.Task AddClientAsync(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient newClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddOrder", ReplyAction="http://tempuri.org/ISkiService/AddOrderResponse")]
        void AddOrder(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order newOrder, System.Guid skiCentreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddOrder", ReplyAction="http://tempuri.org/ISkiService/AddOrderResponse")]
        System.Threading.Tasks.Task AddOrderAsync(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order newOrder, System.Guid skiCentreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddEquipment", ReplyAction="http://tempuri.org/ISkiService/AddEquipmentResponse")]
        void AddEquipment(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Equipment newitem, int count, System.Guid warehouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddEquipment", ReplyAction="http://tempuri.org/ISkiService/AddEquipmentResponse")]
        System.Threading.Tasks.Task AddEquipmentAsync(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Equipment newitem, int count, System.Guid warehouseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddWarehouse", ReplyAction="http://tempuri.org/ISkiService/AddWarehouseResponse")]
        void AddWarehouse(System.Guid skicentreId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISkiService/AddWarehouse", ReplyAction="http://tempuri.org/ISkiService/AddWarehouseResponse")]
        System.Threading.Tasks.Task AddWarehouseAsync(System.Guid skicentreId, string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISkiServiceChannel : Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.ISkiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SkiServiceClient : System.ServiceModel.ClientBase<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.ISkiService>, Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.ISkiService {
        
        public SkiServiceClient() {
        }
        
        public SkiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SkiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter[] GetCenters() {
            return base.Channel.GetCenters();
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter[]> GetCentersAsync() {
            return base.Channel.GetCentersAsync();
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse[] GetWarehouses(System.Guid skiCentreId) {
            return base.Channel.GetWarehouses(skiCentreId);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse[]> GetWarehousesAsync(System.Guid skiCentreId) {
            return base.Channel.GetWarehousesAsync(skiCentreId);
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] GetQuipmentByWarehouseId(System.Guid skiCentreId, System.Guid warehouseId) {
            return base.Channel.GetQuipmentByWarehouseId(skiCentreId, warehouseId);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[]> GetQuipmentByWarehouseIdAsync(System.Guid skiCentreId, System.Guid warehouseId) {
            return base.Channel.GetQuipmentByWarehouseIdAsync(skiCentreId, warehouseId);
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.ClientModel[] GetClients() {
            return base.Channel.GetClients();
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.ClientModel[]> GetClientsAsync() {
            return base.Channel.GetClientsAsync();
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[] GetOrders(int count, int skip) {
            return base.Channel.GetOrders(count, skip);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[]> GetOrdersAsync(int count, int skip) {
            return base.Channel.GetOrdersAsync(count, skip);
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[] GetOrdersByPeriod(System.DateTime stardDate, System.DateTime endDate) {
            return base.Channel.GetOrdersByPeriod(stardDate, endDate);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order[]> GetOrdersByPeriodAsync(System.DateTime stardDate, System.DateTime endDate) {
            return base.Channel.GetOrdersByPeriodAsync(stardDate, endDate);
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Document[] GetDocumentsByClientId(System.Guid clientId) {
            return base.Channel.GetDocumentsByClientId(clientId);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Document[]> GetDocumentsByClientIdAsync(System.Guid clientId) {
            return base.Channel.GetDocumentsByClientIdAsync(clientId);
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] GetCurrentEquipmentsByClientId(System.Guid clientId) {
            return base.Channel.GetCurrentEquipmentsByClientId(clientId);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[]> GetCurrentEquipmentsByClientIdAsync(System.Guid clientId) {
            return base.Channel.GetCurrentEquipmentsByClientIdAsync(clientId);
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] GetCurrentRentEquipments(System.Guid skiCentreId) {
            return base.Channel.GetCurrentRentEquipments(skiCentreId);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[]> GetCurrentRentEquipmentsAsync(System.Guid skiCentreId) {
            return base.Channel.GetCurrentRentEquipmentsAsync(skiCentreId);
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[] GetCurrentFreeEquipments(System.Guid skiCentreId) {
            return base.Channel.GetCurrentFreeEquipments(skiCentreId);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.WarehouseElement[]> GetCurrentFreeEquipmentsAsync(System.Guid skiCentreId) {
            return base.Channel.GetCurrentFreeEquipmentsAsync(skiCentreId);
        }
        
        public Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient GetDetailClientInfo(System.Guid clientId) {
            return base.Channel.GetDetailClientInfo(clientId);
        }
        
        public System.Threading.Tasks.Task<Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient> GetDetailClientInfoAsync(System.Guid clientId) {
            return base.Channel.GetDetailClientInfoAsync(clientId);
        }
        
        public void AddSkiCentre(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter item) {
            base.Channel.AddSkiCentre(item);
        }
        
        public System.Threading.Tasks.Task AddSkiCentreAsync(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.SkiCenter item) {
            return base.Channel.AddSkiCentreAsync(item);
        }
        
        public void AddWarehouseToSkiCentre(System.Guid skiCenterId, Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse item) {
            base.Channel.AddWarehouseToSkiCentre(skiCenterId, item);
        }
        
        public System.Threading.Tasks.Task AddWarehouseToSkiCentreAsync(System.Guid skiCenterId, Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Warehouse item) {
            return base.Channel.AddWarehouseToSkiCentreAsync(skiCenterId, item);
        }
        
        public bool CheckUser(string login, string password) {
            return base.Channel.CheckUser(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserAsync(string login, string password) {
            return base.Channel.CheckUserAsync(login, password);
        }
        
        public void AddClient(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient newClient) {
            base.Channel.AddClient(newClient);
        }
        
        public System.Threading.Tasks.Task AddClientAsync(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.BigClient newClient) {
            return base.Channel.AddClientAsync(newClient);
        }
        
        public void AddOrder(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order newOrder, System.Guid skiCentreId) {
            base.Channel.AddOrder(newOrder, skiCentreId);
        }
        
        public System.Threading.Tasks.Task AddOrderAsync(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Order newOrder, System.Guid skiCentreId) {
            return base.Channel.AddOrderAsync(newOrder, skiCentreId);
        }
        
        public void AddEquipment(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Equipment newitem, int count, System.Guid warehouseId) {
            base.Channel.AddEquipment(newitem, count, warehouseId);
        }
        
        public System.Threading.Tasks.Task AddEquipmentAsync(Artinov.StageOne.SkiCenterManagementSystem.SkiServiceReference.Equipment newitem, int count, System.Guid warehouseId) {
            return base.Channel.AddEquipmentAsync(newitem, count, warehouseId);
        }
        
        public void AddWarehouse(System.Guid skicentreId, string name) {
            base.Channel.AddWarehouse(skicentreId, name);
        }
        
        public System.Threading.Tasks.Task AddWarehouseAsync(System.Guid skicentreId, string name) {
            return base.Channel.AddWarehouseAsync(skicentreId, name);
        }
    }
}
